### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#18]
So forms are the worst. I would like a lot of control over form styling, and I think that means we're not going to be able to use the default forms, right? What's the easiest way for us to switch from default forms to custom forms?

**Comment by melinath** [comment]
What do you mean? Slash... there are things like floppyforms out there which people can use. Ask @harrislapiroff whether he's got a favorite.

**Comment by nmorduch** [comment]
I need to put various divs inside the forms and classes on things inside the forms, and I believe that I cannot do that when the forms are automatically generated.

**Comment by harrislapiroff** [comment]
Form handling in Django _does_ get slightly more granular than we've got it now. I tend to use `{{ form.as_table }}` and `{{ form.as_p }}` as more like placeholders until forms can be more designed. Once you hit that point you should be using something more like:

``` html+django
<form ...>
    {% csrf_token %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="control-group">
            {{ field.label_tag }}
            {{ field }}
        </div>
    {% endfor %}
    <button>Submit</button>
</form>
```

or whatever it is you need to do. See the [documentation](https://docs.djangoproject.com/en/dev/topics/forms/#customizing-the-form-template) for more details.

That having been said, Django's built-in widget rendering is still _very_ limited and if you find that you need to start doing even more advanced stuff than is allowed by it (e.g., add classes to the `<input />`s themselves, use HTML5 input types, et. al.) then we'll need to adopt something like [floppyforms](http://django-floppyforms.readthedocs.org/en/latest/) that allows widget templating. I don't have a favorite because I've never used one. Floppyforms is the one I've heard the most about. If we want to go that route one of us should do some research and then just [pick one](https://www.djangopackages.com/grids/g/forms/) and integrate it into the project.

**Comment by melinath** [comment]
(Django uses some HTML5 input types now.)

**Comment by nmorduch** [comment]
I feel like we used floppyforms for something once but maybe Violet did that? Maybe on the News Center.

**Comment by nmorduch** [comment]
I think that in order to use chosen, we will need to use floppyforms or similar. (chosen uses classes on <select>.) Can one of you get that set up?

**Comment by melinath** [comment]
Chosen is a jQuery add-on... the classes in the documentation are just used as hooks; I don't think they have any other significance. You could also just do:

``` js
$('input').chosen();
```

**Comment by nmorduch** [comment]
For scoping, I suppose we could put classes on the forms and then reference the child inputs, but I think that that is sloppy. I also want to add classes to make them more bootstrappy. Anyway, it looks like this is where we're going anyway.

**Comment by nmorduch** [comment]
Also: Can the form stuff be on a new branch? Since it is a multi-commit process.
I am not sure the easiest way to separate this out from the current commits.

**Comment by melinath** [comment]
Sure, you can put the form stuff on a new branch, if you like.

I'm pretty sure this basic version that I just stuck in uses bootstrap 2.0 or something, so it will need to be updated.

**Comment by nmorduch** [comment]
Closing this because I think it is covered by a number of individual issues.
