### ISSUE TITLE
Add note that old URLs will stop working on slug change

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#6]
When you change your group slug, then hit back, you get a 404 because going back takes you to a url with your old slug. Should you secretly keep your old slug too? Maybe temporarily? Maybe successful edits should take you back to your group page rather than keeping you on the edit page?

**Comment by melinath** [comment]
... I thought I fixed this.

**Comment by melinath** [comment]
Oh, you're hitting back. Yes. that would result in a 404, but that's expected behavior, not a bug. People are expected to navigate with provided links rather than the back button. Granted, the current design... leaves something to be desired, in that it doesn't exist.

I would prefer not to keep the old slug at this time. It gets really complicated really fast.

**Comment by nmorduch** [comment]
Ok. We'll have a link and then see if that stops me from trying to use the back button. I do think it is very reasonable to navigate using the back button, though (and recent versions of the Mac OS encourage this with silly swipy things) so I think I might also put a note saying that you won't be able to navigate back and you need to change your records of your url.

**Comment by melinath** [comment]
That seems reasonable. We could even do what Github does and make them enter a long exact phrase before changing the name - but I think that would be too heavy.
